version: 0.0
os: linux 
files:
  - source:  /
    destination: /tmp/Angular2CodeDeploy
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 50
      runas: ec2-user
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 10
      runas: ec2-user
  ValidateService:
    - location: scripts/validate-service.sh    
      timeout: 10
      runas: ec2-user
